# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`

version: '3.7'

services:
  selenium-debug:
    image: selenium/standalone-chrome-debug:3.141.59-20200826
    ports:
      - "4445:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm